---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(here)
loc <- here("DOC","klapman_report.pdf")
loc
```

# 2018 U.S. Midterm Popular Vote Estimation

The goal of project is to explore polling data for the 2018 U.S. midterm elections and try to estimate the overall house of representatives popular vote proportions. You can find the log of data exploration in the DOC folder, as well as my final report. The presentation for this project can be found in the PRES folder.

* [Link to final report.](https://github.com/ST541-Fall2018/mklapman-project-elections/blob/master/DOC/klapman_report.pdf)  

* [Link to presentation.](/cloud/project/PRES/presentation.pdf)  (Can't get these to work right now)

In this project I used four main methods of analyzing and estimating the popular vote in the 2018 U.S. Midterm elections. These methods included a naive estimate, a weighting scheme, subsetting the data in order to capture only the most representative samples, and relative support. All of these were assessed and a summary of them can be found in my report.

There is some analysis that did not make it into the report, namely regression analysis and exploring other datasets. Documentation on these attempts can be found in the DOC folder as well.
