---
title: "regression"
author: "Matt Klapman"
date: "12/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(here)
library(rsample)
devtools::load_all()
```

```{r}
true_result <- 53.1-45.2
rcp_midterms <- read_csv(here("DATA","RCP_midterms.csv"))
rcp_midterms <- rcp_midterms %>% mutate(prop_diff = (Dem - Rep)/100, ord = 1:length(prop_diff),
                                        Dates = as.Date(Dates, "%m/%d/%Y", 
                                                        origin = as.Date("01/01/2017","%m/%d/%Y")),
                                        #tr_num_dates = trunc(as.numeric(Dates) - 17167, prec = -1)/10
                                        num_dates = as.numeric(Dates) - 17167,
                                        prob = num_dates/sum(num_dates),
                                        rel_Dem = Dem/(Dem + Rep), 
                                        rel_Rep = Rep/(Dem + Rep), 
                                        rel_diff = rel_Dem - rel_Rep,
                                        prob_full = double(length(prob)))

rcp_midterms$prob_full[rcp_midterms$SampType == "LV"] <-
  rcp_midterms$prob[rcp_midterms$SampType == "LV"] + 1/3/309

rcp_midterms$prob_full[rcp_midterms$SampType == "RV"] <-
  rcp_midterms$prob[rcp_midterms$SampType == "RV"] + 2/9/309

rcp_midterms$prob_full[rcp_midterms$SampType == "A"] <-
  rcp_midterms$prob[rcp_midterms$SampType == "A"] + 1/9/309
```





```{r}
ggplot(data = rcp_midterms) + 
  geom_smooth(aes(x = Dates, y = Dem, weight = SampSize), color = "darkblue", se = FALSE) +
  geom_smooth(aes(x = Dates, y = Rep, weight = SampSize), color = "darkred", se = FALSE)


ggplot(data = rcp_midterms) + 
  geom_smooth(aes(x = Dates, y = rel_diff), se = FALSE)

ggplot(data = rcp_midterms) +
  geom_point(aes(x = Dates, y = prop_diff, color = SampType))
```


Some GLM stuff:

```{r}
mod1 <- glm(prop_diff ~ SampType + Dates, data = rcp_midterms, weights = SampSize)

rcp_midterms$prop_diff
summary(mod1)
plot(mod1)

mod1_df <- fortify(mod1)

ggplot(data = mod1_df) + geom_point(aes(x = .fitted, y = .stdresid))

ggplot(data = mod1_df) + geom_point(aes(x = Dates, y = .fitted, color = SampType))
```


Doing a generalized linear model may be unreasonable considering I will end up having some negative values as my response is some difference in proportions. So, any kind of logarithmic link function will be invalid. 